export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST"
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS"
export const GET_BOOKINGS_ERROR = "GET_BOOKINGS_ERROR"


export const GET_CUSTOMER_CARE_BOOKINGS_REQUEST = "GET_CUSTOMER_CARE_BOOKINGS_REQUEST"
export const GET_CUSTOMER_CARE_BOOKINGS_SUCCESS = "GET_CUSTOMER_CARE_BOOKINGS_SUCCESS"
export const GET_CUSTOMER_CARE_BOOKINGS_ERROR = "GET_CUSTOMER_CARE_BOOKINGS_ERROR"

export const GET_DATE_BOOKINGS_REQUEST = "GET_DATE_BOOKINGS_REQUEST"
export const GET_DATE_BOOKINGS_SUCCESS = "GET_DATE_BOOKINGS_SUCCESS"
export const GET_DATE_BOOKINGS_ERROR = "GET_DATE_BOOKINGS_ERROR"

export const CLEAR_BOOKINGS_ERRORS = "CLEAR_BOOKINGS_ERRORS"