export const CREATE_COUPAN_REQUEST = "CREATE_COUPAN_REQUEST"
export const CREATE_COUPAN_SUCCESS = "CREATE_COUPAN_SUCCESS"
export const CREATE_COUPAN_ERROR = "CREATE_COUPAN_ERROR"

export const FETCH_ALL_COUPANS_REQUEST = "FETCH_ALL_COUPANS_REQUEST"
export const FETCH_ALL_COUPANS_SUCCESS = "FETCH_ALL_COUPANS_SUCCESS"
export const FETCH_ALL_COUPANS_ERROR = "FETCH_ALL_COUPANS_ERROR"

export const DELETE_COUPAN_REQUEST = "DELETE_COUPAN_REQUEST"
export const DELETE_COUPAN_SUCCESS = "DELETE_COUPAN_SUCCESS"
export const DELETE_COUPAN_ERROR = "DELETE_COUPAN_ERROR"
export const DELETE_COUPAN_RESET = "DELETE_COUPAN_RESET"

export const CLEAR_COUPAN_ERRORS = "CLEAR_COUPAN_ERRORS"