export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST"
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS"
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR"

export const GET_SINGLE_EMPLOYEE_REQUEST = "GET_SINGLE_EMPLOYEE_REQUEST"
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS"
export const GET_SINGLE_EMPLOYEE_ERROR = "GET_SINGLE_EMPLOYEE_ERROR"

export const GET_ALL_EMPLOYEES_REQUEST = "GET_ALL_EMPLOYEES_REQUEST"
export const GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS"
export const GET_ALL_EMPLOYEES_ERROR = "GET_ALL_EMPLOYEES_ERROR"

export const EDIT_EMPLOYEE_REQUEST = "EDIT_EMPLOYEE_REQUEST"
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS"
export const EDIT_EMPLOYEE_ERROR = "EDIT_EMPLOYEE_ERROR"
export const EDIT_EMPLOYEE_RESET = "EDIT_EMPLOYEE_RESET"

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR"

export const DELETE_EMPLOYEE_FROM_SERVICE_REQUEST = "DELETE_EMPLOYEE_FROM_SERVICE_REQUEST"
export const DELETE_EMPLOYEE_FROM_SERVICE_SUCCESS = "DELETE_EMPLOYEE_FROM_SERVICE_SUCCESS"
export const DELETE_EMPLOYEE_FROM_SERVICE_ERROR = "DELETE_EMPLOYEE_FROM_SERVICE_ERROR"

export const CLEAR_EMPLOYEES_ERRORS = "CLEAR_EMPLOYEES_ERRORS"