export const ADD_OFFER_IMAGES_REQUEST = "ADD_OFFER_IMAGES_REQUEST"
export const ADD_OFFER_IMAGES_SUCCESS = "ADD_OFFER_IMAGES_SUCCESS"
export const ADD_OFFER_IMAGES_ERROR = "ADD_OFFER_IMAGES_ERROR"
export const ADD_OFFER_IMAGES_RESET = "ADD__OFFER_IMAGES_RESET"

export const GET_OFFER_IMAGES_REQUEST = "GET_OFFER_IMAGES_REQUEST"
export const GET_OFFER_IMAGES_SUCCESS = "GET_OFFER_IMAGES_SUCCESS"
export const GET_OFFER_IMAGES_ERROR = "GET_OFFER_IMAGES_ERROR"
export const GET_OFFER_IMAGES_RESET = "GET_OFFER_IMAGES_RESET"

export const DELETE_OFFER_IMAGES_REQUEST = "DELETE_OFFER_IMAGES_REQUEST"
export const DELETE_OFFER_IMAGES_SUCCESS = "DELETE_OFFER_IMAGES_SUCCESS"
export const DELETE_OFFER_IMAGES_ERROR = "DELETE_OFFER_IMAGES_ERROR"
export const DELETE_OFFER_IMAGES_RESET = "DELETE_OFFER_IMAGES_RESET"

export const CLEAR_ERRORS="CLEAR_ERRORS"