export const FETCH_ALL_SALOONS_REQUEST = "FETCH_ALL_SALOONS_REQUEST"
export const FETCH_ALL_SALOONS_SUCCESS = "FETCH_ALL_SALOONS_SUCCESS"
export const FETCH_ALL_SALOONS_ERROR = "FETCH_ALL_SALOONS_ERROR"

export const GET_SINGLE_SALOON_REQUEST = "GET_SINGLE_SALOON_REQUEST"
export const GET_SINGLE_SALOON_SUCCESS = "GET_SINGLE_SALOON_SUCCESS"
export const GET_SINGLE_SALOON_ERROR = "GET_SINGLE_SALOON_ERROR"

export const UPDATE_SALOON_TAGS_REQUEST = "UPDATE_SALOON_TAGS_REQUEST"
export const UPDATE_SALOON_TAGS_SUCCESS = "UPDATE_SALOON_TAGS_SUCCESS"
export const UPDATE_SALOON_TAGS_ERROR = "UPDATE_SALOON_TAGS_ERROR"

export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR"

export const ADD_NEW_SERVICES_REQUEST = "ADD_NEW_SERVICES_REQUEST"
export const ADD_NEW_SERVICES_SUCCESS = "ADD_NEW_SERVICES_SUCCESS"
export const ADD_NEW_SERVICES_ERROR = "ADD_NEW_SERVICES_ERROR"

export const UPDATE_SERVICES_REQUEST = "UPDATE_SERVICES_REQUEST"
export const UPDATE_SERVICES_SUCCESS = "UPDATE_SERVICES_SUCCESS"
export const UPDATE_SERVICES_ERROR = "UPDATE_SERVICES_ERROR"
export const UPDATE_SERVICES_RESET = "UPDATE_SERVICES_RESET"

export const ACCOUNTS_REQUEST = "ACCOUNTS_REQUEST"
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS"
export const ACCOUNTS_ERROR = "ACCOUNTS_ERROR"


export const ADD_IMAGES_REQUEST = "ADD_IMAGES_REQUEST"
export const ADD_IMAGES_SUCCESS = "ADD_IMAGES_SUCCESS"
export const ADD_IMAGES_ERROR = "ADD_IMAGES_ERROR"
export const ADD_IMAGES_RESET = "ADD_IMAGES_RESET"

export const DELETE_IMAGES_REQUEST = "DELETE_IMAGES_REQUEST"
export const DELETE_IMAGES_SUCCESS = "DELETE_IMAGES_SUCCESS"
export const DELETE_IMAGES_ERROR = "DELETE_IMAGES_ERROR"
export const DELETE_IMAGES_RESET = "DELETE_IMAGES_RESET"

export const DELETE_SALON_DATA_REQUEST = "DELETE_SALON_DATA_REQUEST"
export const DELETE_SALON_DATA_SUCCESS = "DELETE_SALON_DATA_SUCCESS"
export const DELETE_SALON_DATA_ERROR = "DELETE_SALON_DATA_ERROR"
export const DELETE_SALON_DATA_RESET = "DELETE_SALON_DATA_RESET"

export const CLEAR_SALOON_ERROR = "CLEAR_SALOON_ERROR"

