export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_ERROR = "LOAD_USER_ERROR"


export const CARE_USER_REQUEST = "CARE_USER_REQUEST"
export const CARE_USER_SUCCESS = "CARE_USER_SUCCESS"
export const CARE_USER_ERROR = "CARE_USER_ERROR"

export const CLEAR_ERRORS="CLEAR_ERRORS"
